---
title: "PS 109 Section 10_raw"
author: "Johanna Reyes O."
date: "2023-04-14"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Plotting with 'ggplot' (a very, very powerful tool!)

## Setting up 
```{r}
#install package 'tidyverse'- for desktop users


#load the packages
library(tidyverse)
library(IRkernel)
library(dplyr)
```

## Bring in the data
```{r}
#load the 'anes' data 

#preview the data


```
Today, we will be using the 'trustgov_trustgrev' and 'dem_hisptyp_1st' variables. 

* What kind of variables are these?
* What does the 'trustgov_trustgrev' measure? 

```{r}
# Let's start with a barplot

#Check for how many observations we have data for both variables

#Note: all ggplots start with the same baseline: ggplot(df, aes(x = , y = )), and you add components from there, using the + sign





```


```{r}
#subset variables so we only look at the continuous measures (1-7 for 'dem_hisptyp_1st' and 1-5 for 'trustgov_trustgrev')

#Two options

dt %>%
  filter(between(x, 1, 3), between(y, 1, 5))

dt %>%
  filter(x in %>% c(1,2), y in %>% c(1:5))


#check for how many observations we have data for both variables

#plot bar plot, subsetting the data first, using the following syntax

dt %>%
  filter(between(x, 1, 3), between(y, 1, 5)) %>%
  ggplot(dt, aes(x = x, y = y)) +
  geom_bar(stat = "identity") #this selects the type of plot. 'identity' 
  geom_col() #alternative, does not perform any calculation with the data


#what do we need to fix here?

#plot by mean per group

#1. Mexican
#2. Mexican-American 
#3. Chicano
#4. Puerto Rican 
#5. Cuban 
#6. Cuban-American
#7. Other

dt %>%
  filter(between(x, 1, 7), between(y, 1, 5)) %>%
  group_by(x) %>% 
  summarize(mean_y = mean(y, na.rm = TRUE)) %>%
  
  ggplot(aes(x = reorder(x, (mean_y)), y = y, fill = y)) +
  geom_bar(stat = "identity") +
  scale_fill_gradient(low = "lightblue", high = "darkblue", name = "name") +
  theme_classic() + #optional, try different themes and see which you like most
  xlab("X label") +
  ylab("Y label") +
  scale_x_discrete(labels = c("label 1", "Label 2"...)

ggsave("name.png")
```

* How would you interpret this plot? 

```{r}
#Redo but now let's compare trust levels only for Puerto Ricans and Cubas. Plot a density plot, make sure to give them each a different color to differentiate. 

anes %>%
  #filter dem_hisptyp_1st %>%
  
  ggplot(aes(x = , fill = factor(hisp type))) +
  geom_density(alpha = 0.5) + #you can select diffent levels of color transparency
  scale_fill_manual(values = c("blue", "lightblue")) + #pick your own colors, try a Hex scale
  xlab("X label") +
  ylab("Density") +
  ggtitle("Title") +
  labs(fill = "Legend Name") +
  theme_classic() #pick your favorite

```

* How would you interpret this other plot? What if we were to compare other groups; what would you expect?